version: '3'
services:
  scraper:
    build: ./
    links:
      - splash
      - mysql
    volumes:
      - ./app:/app
  tor-privoxy:
    image: zeta0/alpine-tor:latest
    ports:
      - 8118:8118
    environment:
      tors: 40
      privoxy: 1
      max_circuit_dirtiness: 20
    restart: always
  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
    volumes:
      - ./proxy-profiles:/etc/splash/proxy-profiles:ro
    links:
      - tor-privoxy
    restart: always
  mysql:
    image: mysql:latest
    container_name: charts_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: charts_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 9000000000
    restart: always
    ports:
      - 8183:80

volumes:
  mysql-data: